const tintColorLight = '#5964E8';
const tintColorDark = '#F7F7F7';

export default {
  light: {
    text: '#333',
    background: '#F7F7F7',
    tint: tintColorLight,
    tabIconDefault: '#ccc',
    tabIconSelected: tintColorLight,
    primaryColor: "#5964E8",
    secondaryColor: "4CABEB",
    backgroundInputColor:"#fff",
    borderInputColor: "#ddd",
    shadowInputColor: "#000",
    placeholderTextColor:"#888",
    errorColor:"#f35369",
    labelColor: "#333",
    backgroundCheckBoxColor: '#fff',
    activeCheckBoxColor: '#5964E8',
    textCheckBoxColor: '#333',
    iconCheckBoxColor: '#64748b',
  },
  dark: {
    text: '#F7F7F7',
    background: '#1c1d22',
    tint: tintColorDark,
    tabIconDefault: '#ccc',
    tabIconSelected: tintColorDark,
    backgroundInputColor:"#111216",
    borderInputColor: "#1e1f22",
    shadowInputColor: "#1e1f22",
    placeholderTextColor:"#888",
    errorColor:"#f35369",
    labelColor: "#888",
    backgroundCheckBoxColor: '#111216',
    activeCheckBoxColor: '#4F5DFF',
    textCheckBoxColor: '#f0f0f0',
    iconCheckBoxColor: '#b0b0b0',
  },
};
